firebase.project.id=csc207-cfda3
firebase.database.url=https://csc207-cfda3-default-rtdb.firebaseio.com
firebase.service.account.path=resources/csc207-cfda3-firebase-adminsdk-fbsvc-5f9167c0b2.json
firebase.use.default.credentials=false
